const CONSTANT = {
    USER_NAME: "userName",
    PASSWORD: "password",
    ROOM_ID: "roomId",
    IS_LOCKED: "isLocked",
    TIME_FORMAT: "HH:mm:ss",
    DATE_FORMAT: "DD/MM/YYYY",
    ROOM_ID_LENGTH: 6,
    USER_NAME_MAX_LENGTH: 20,
    ROOM_PASSWORD_MAX_LENGTH: 10,
    ROOM_PASSWORD_MIN_LENGTH: 6,
    POOR_NETWORK_RTT: 500,
    POOR_NETWORK_DOWNBPS: 500000,
    GOOD_NETWORK_RTT: 200,
    GOOD_NETWORK_DOWNBPS: 1000000,
}

export default CONSTANT;
